### ISSUE TITLE
Begleitseminar ZuLa Informatik

### ISSUE THREAD

**Issue by motrell** [Idontker/LA-Notenrechner#20]
Problem: Laut (zumindest alter) INF-LA-FPO muss man 2,5 ECTS WPB für das Begleitseminar zur Zula aufwenden, falls man die in Info schreibt. Mir ist grade beim testen nicht bewusst gewesen, wie ich das als Nutzer berücksichtigen muss

**Comment by Idontker** [comment]
Du kannst es eintragen als Wahlpflichtfach 2.5 ECTS. 
Ist so viel ich weiß, ein Randfall unter den Modulen der Informatik und hatten daher auf einen leichten Fix gesetzt.
